import { config } from "dotenv";
import { promises as fs } from "fs";
import path from "path";
import { spawn, spawnSync, type ChildProcess } from "child_process";
import ffmpegPath from "ffmpeg-static";

/**
 * One-command launch-video asset capture.
 *
 *   pnpm capture-assets            full run (migrate → seed → build → capture)
 *   pnpm capture-assets --skip-build   reuse the existing .next build
 *
 * Reads `.env.capture` (NOT `.env`) so the run can never point at the real
 * Supabase database. See `.env.capture.example`.
 */

const ROOT = process.cwd();
const OUT_DIR = path.join(ROOT, "launch-video-assets");
const RAW_DIR = path.join(OUT_DIR, ".raw");
const PORT = Number(process.env.CAPTURE_PORT ?? 3210);
const BASE_URL = `http://127.0.0.1:${PORT}`;

const skipBuild = process.argv.includes("--skip-build");

function step(msg: string) {
  console.log(`\n\x1b[1m▸ ${msg}\x1b[0m`);
}

function run(cmd: string, args: string[], env: NodeJS.ProcessEnv) {
  const r = spawnSync(cmd, args, { stdio: "inherit", env, cwd: ROOT });
  if (r.status !== 0) throw new Error(`${cmd} ${args.join(" ")} failed (${r.status})`);
}

async function waitForServer(url: string, timeoutMs = 90_000) {
  const t0 = Date.now();
  while (Date.now() - t0 < timeoutMs) {
    try {
      const res = await fetch(url, { redirect: "manual" });
      if (res.status > 0) return;
    } catch {
      /* not up yet */
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error(`Server never became ready at ${url}`);
}

/**
 * Playwright writes VP8 .webm at whatever rate the compositor produced. The
 * brief asks for 60fps MP4, so we re-time to a constant 60fps — note this is
 * frame duplication, not interpolation: motion is as smooth as it was captured,
 * the container is just 60fps so it drops straight into a 60fps timeline.
 */
async function transcode(): Promise<void> {
  const files = (await fs.readdir(RAW_DIR)).filter((f) => f.endsWith(".webm"));
  for (const f of files) {
    const src = path.join(RAW_DIR, f);
    const dest = path.join(OUT_DIR, f.replace(/\.webm$/, ".mp4"));
    run(
      ffmpegPath as string,
      [
        "-y", "-i", src,
        "-t", "4",
        // Recorded 1:1 at 1920×1080, so no rescale — any scaling here would
        // either soften the UI or re-introduce the padding bug.
        "-vf", "fps=60",
        "-c:v", "libx264", "-preset", "slow", "-crf", "16",
        "-pix_fmt", "yuv420p", "-movflags", "+faststart",
        "-an",
        dest,
      ],
      process.env,
    );
  }
}

async function writeReadme(
  shots: { file: string; what: string }[],
  meta: { placeholderVideo: boolean },
) {
  const rows = shots.map((s) => `| \`${s.file}\` | ${s.what} |`).join("\n");
  const body = `# Launch video assets

Generated by \`pnpm capture-assets\`. Everything here is captured from the real
app against a local demo database — no mockups, no Photoshop.

- **Stills:** PNG, 2560×1440 (1280×720 CSS at 2× DPR).
- **Recordings:** MP4 / H.264 / 60fps / 4s, **1920×1080**, no audio. Recorded 1:1
  rather than at 2× — Playwright's \`recordVideo.size\` does not scale the
  screencast by \`deviceScaleFactor\`, so a larger canvas only pads the frame.
- **Element exports:** PNG with a transparent background, for compositing as
  floating overlays.
- **No cursor** appears in any recording. Playwright doesn't paint one, and a
  drawn-on pointer reads worse than clean UI in a fast cut. The clicks and
  scrolls are real — only the pointer is absent.

## Files

| File | What it shows |
| --- | --- |
${rows}

## Re-running

\`\`\`bash
pnpm capture-assets              # migrate → seed → build → capture
pnpm capture-assets --skip-build # reuse the existing .next build
\`\`\`

Requires a **local** Postgres — see \`.env.capture.example\`. The seed refuses to
run against a non-local host, because it deletes content rows.

## Notes

${
  meta.placeholderVideo
    ? `- ⚠️ **The lecture video is a placeholder.** No real lecture footage was
  available, so the player shows an abstract brand-coloured gradient rather than
  invented "lecture" content. Drop a real recording at
  \`capture/assets/lecture.mp4\` and re-run — the script prefers it automatically.`
    : `- The lecture video came from \`capture/assets/lecture.mp4\`.`
}
- The 60fps MP4s are re-timed from Playwright's ~25fps screencast by frame
  duplication. They cut cleanly into a 60fps timeline, but slowing them below
  ~40% will show the source cadence.
`;
  await fs.writeFile(path.join(OUT_DIR, "README.md"), body);
}

async function main() {
  const envPath = path.join(ROOT, ".env.capture");
  if (!(await fs.access(envPath).then(() => true).catch(() => false))) {
    console.error(
      `\nMissing .env.capture — copy .env.capture.example and point DATABASE_URL at a local Postgres.\n`,
    );
    process.exit(1);
  }
  config({ path: envPath, override: true });

  const env: NodeJS.ProcessEnv = {
    ...process.env,
    NODE_ENV: "production",
    PORT: String(PORT),
    APP_URL: BASE_URL,
  };

  step("Applying migrations to the capture database");
  run("pnpm", ["exec", "prisma", "migrate", "deploy"], env);

  step("Seeding demo data");
  const { seedDemo } = await import("./demo-data");
  const demo = await seedDemo({
    storageDir: process.env.STORAGE_DIR ?? "./storage",
    ffmpegPath: ffmpegPath as string,
  });

  if (!skipBuild) {
    step("Building the app (production build — no dev overlay in the footage)");
    run("pnpm", ["exec", "next", "build"], env);
  }

  step(`Starting the app on ${BASE_URL}`);
  let server: ChildProcess | undefined;
  try {
    server = spawn("pnpm", ["exec", "next", "start", "-p", String(PORT)], {
      env,
      cwd: ROOT,
      stdio: "ignore",
    });
    await waitForServer(BASE_URL);

    step("Capturing");
    await fs.rm(OUT_DIR, { recursive: true, force: true });
    const { capture } = await import("./capture");
    const shots = await capture({
      baseURL: BASE_URL,
      outDir: OUT_DIR,
      rawVideoDir: RAW_DIR,
      ids: demo.ids,
      student: { username: demo.student.username, password: demo.student.password },
    });

    step("Transcoding to 60fps MP4");
    await transcode();
    await fs.rm(RAW_DIR, { recursive: true, force: true });

    await writeReadme(shots, { placeholderVideo: demo.placeholderVideo });
    step(`Done — ${shots.length} assets in ./launch-video-assets`);
  } finally {
    server?.kill("SIGTERM");
  }
}

main().catch((e) => {
  console.error("\nCapture failed:", e);
  process.exit(1);
});
